### ISSUE TITLE
Ordering of edge function vectors

### ISSUE THREAD

**Issue by adamrt** [gustavopezzi/triangle-rasterizer-float#1]
Hi Gustavo! I've been through your 3D from scratch course multiple times, but I didn't know about this rasterization video until now. I've been implementing it but I have an issue when it comes to texture mapping.

In your code [here](https://github.com/gustavopezzi/triangle-rasterizer-float/blob/main/src/main.c#L85), in the video you mention this order doesn't matter(when you're writing it the first time at the [52:05 mark](https://www.youtube.com/watch?v=k5wtuKWmV48&t=3125s)).

```
// Compute the edge functions for the fist (top-left) point
vec2_t p0 = { x_min + 0.5f , y_min + 0.5f };
float w0_row = edge_cross(&v1, &v2, &p0) + bias0;
float w1_row = edge_cross(&v2, &v0, &p0) + bias1;
float w2_row = edge_cross(&v0, &v1, &p0) + bias2;
```

I noticed here and other places you  use `v1,v2` for `w0`. Intuitively I would think `w0` should be `v0,v1` - just because that's naturally the first edge. For just filling in a triangle its hard to tell there is an issue. But when you start to get the alpha, beta and gamma for texture mapping, that orders seems like it matters.

Using `v1, v2, p` for `w0` makes my `alpha = w0 / area` work as expected. 

Can you explain the relationship here? Why must I have that order.

Thank you!

**Comment by adamrt** [comment]
Wait I think it just clicked! Is it because when we are doing the division with `area`, we want to know the the weight for (alpha) based on the weights of the other two opposing vertices (v1 and v2).

**Comment by gustavopezzi** [comment]
> Wait I think it just clicked! Is it because when we are doing the division with `area`, we want to know the the weight for (alpha) based on the weights of the other two opposing vertices (v1 and v2).

That is correct! At first, the order was not important... but later in our code (for the barycentric coordinates alpha/beta/gamma) the order matters. 🙂

**Comment by adamrt** [comment]
Thanks so much Keep up the great work Gustavo!
